; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "OpenDDR"
#define MyAppVersion "1.0"
#define MyAppPublisher "Hamburgerghini1"
#define MyAppURL "https://github.com/hamburgerghini1/build-stepmania-ddr"
#define MyAppExeName "OpenDDR-debug.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A0549166-A843-4328-A7BF-D788BF4FDAF7}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=C:\Users\tommi\Downloads\stepmania-ddr-5_1-new\LICENSE
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\tommi\Downloads
OutputBaseFilename=openddr-setup
SetupIconFile=C:\Users\tommi\Downloads\stepmania-ddr-5_1-new\OpenDDR-debug_1007.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\tommi\Downloads\stepmania-ddr-5_1-new\Program\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tommi\Downloads\stepmania-ddr-5_1-new\Program\avcodec-55.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tommi\Downloads\stepmania-ddr-5_1-new\Program\avformat-55.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tommi\Downloads\stepmania-ddr-5_1-new\Program\avutil-52.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tommi\Downloads\stepmania-ddr-5_1-new\Program\mapconv.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tommi\Downloads\stepmania-ddr-5_1-new\Program\mapconv.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tommi\Downloads\stepmania-ddr-5_1-new\Program\OpenDDR-debug.map"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tommi\Downloads\stepmania-ddr-5_1-new\Program\OpenDDR-debug.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tommi\Downloads\stepmania-ddr-5_1-new\Program\OpenDDR-debug.vdi"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tommi\Downloads\stepmania-ddr-5_1-new\Program\parallel_lights_io.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tommi\Downloads\stepmania-ddr-5_1-new\Program\swscale-2.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

